insert into talent(talent_type) values("국어");
insert into talent(talent_type) values("수학");
insert into talent(talent_type) values("영어");
insert into talent(talent_type) values("피아노");
insert into talent(talent_type) values("노래");
insert into talent(talent_type) values("마술");
insert into talent(talent_type) values("보건 및 의료");
insert into talent(talent_type) values("무료법률상담");
insert into talent(talent_type) values("청소년 상담");
insert into talent(talent_type) values("JAVA 코딩 교육");

insert into person(benefit, donation, email, name) values(1, 2, "a@asdf", "a");
insert into person(benefit, donation, email, name) values(2, 3, "b@asdf", "b");
insert into person(benefit, donation, email, name) values(3, 4, "c@asdf", "c");
insert into person(benefit, donation, email, name) values(4, 5, "d@asdf", "d");
insert into person(benefit, donation, email, name) values(5, 6, "e@asdf", "e");
insert into person(benefit, donation, email, name) values(6, 7, "f@asdf", "f");
insert into person(benefit, donation, email, name) values(7, 8, "g@asdf", "g");
insert into person(benefit, donation, email, name) values(8, 9, "h@asdf", "h");
insert into person(benefit, donation, email, name) values(9, 10, "i@asdf", "i");
insert into person(benefit, donation, email, name) values(10, null, "j@asdf", "j");
insert into person(benefit, donation, email, name) values(null, 1, "k@asdf", "k");
insert into person(benefit, donation, email, name) values(1, 2, "l@asdf", "l");
insert into person(benefit, donation, email, name) values(2, 3, "m@asdf", "m");
insert into person(benefit, donation, email, name) values(3, 4, "n@asdf", "n");
insert into person(benefit, donation, email, name) values(4, 5, "o@asdf", "o");
insert into person(benefit, donation, email, name) values(5, 6, "p@asdf", "p");
insert into person(benefit, donation, email, name) values(6, 7, "q@asdf", "q");
insert into person(benefit, donation, email, name) values(7, 8, "r@asdf", "r");
insert into person(benefit, donation, email, name) values(8, 9, "s@asdf", "s");
insert into person(benefit, donation, email, name) values(9, 10, "t@asdf", "t");
insert into person(benefit, donation, email, name) values(10, null, "u@asdf", "u");
insert into person(benefit, donation, email, name) values(2, 1, "v@asdf", "v");
insert into person(benefit, donation, email, name) values(1, 2, "w@asdf", "w");
insert into person(benefit, donation, email, name) values(2, 3, "x@asdf", "x");
insert into person(benefit, donation, email, name) values(3, 4, "y@asdf", "y");
insert into person(benefit, donation, email, name) values(4, 5, "z@asdf", "z");
